WORKSPACE_DIR = "tasks/task6v2/workspace"
DOCS_DIR = "tasks/task6v2/docs"
BACKUP_DIR = "backups"

GENERATE_GRAPHS=False
GRAPHS_DIR="graphs"

WORKER_RECURSION_LIMIT=100
TEAM_RECURSION_LIMIT=1000
SOFTWARE_HOUSE_RECURSION_LIMIT=100